name: SLSA releaser
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "*"

permissions: read-all

jobs:
  # Generate ldflags dynamically.
  args:
    runs-on: ubuntu-latest
    outputs:
      ldflags: ${{ steps.ldflags.outputs.value }}
    steps:
      - id: checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v2.3.4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "value=$(./scripts/version-ldflags)" >> "$GITHUB_OUTPUT"

  # Trusted builder.
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.6.0 # v1.2.0
    with:
      go-version: 1.19
      evaluated-envs: "VERSION_LDFLAGS:${{needs.args.outputs.ldflags}}"
